# Generated by Django 3.1.5 on 2021-01-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=100000000)),
                ('hasNds', models.BooleanField(default=False)),
                ('nds', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('parsed', models.TextField(blank=True)),
            ],
        ),
    ]
