# Generated by Django 3.1.5 on 2021-01-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='nds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='parsed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
