# Generated by Django 3.1.5 on 2021-01-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210129_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='nds',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10000000000000000),
        ),
    ]
