# Generated by Django 3.1.5 on 2021-01-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210129_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='nds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
